set_property IOSTANDARD LVCMOS33 [get_ports a]
set_property IOSTANDARD LVCMOS33 [get_ports b]
set_property IOSTANDARD LVCMOS33 [get_ports output]
set_property IOSTANDARD LVCMOS33 [get_ports sel]

set_property OFFCHIP_TERM NONE [get_ports output]
set_property PACKAGE_PIN L5 [get_ports a]
set_property PACKAGE_PIN L4 [get_ports b]
set_property PACKAGE_PIN M4 [get_ports sel]
set_property PACKAGE_PIN J3 [get_ports output]
set_property DRIVE 12 [get_ports output]
