set_property PACKAGE_PIN L5 [get_ports a]
set_property PACKAGE_PIN L4 [get_ports b]
set_property PACKAGE_PIN J3 [get_ports c]
set_property IOSTANDARD LVCMOS33 [get_ports a]
set_property IOSTANDARD LVCMOS33 [get_ports b]
set_property IOSTANDARD LVCMOS33 [get_ports c]
